@startuml container
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons
!define DEVICONS2 https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons2
!define MATERIAL https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/material
!define FONTAWESOME https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome-5
!include DEVICONS/angular.puml
!include DEVICONS2/facebook.puml
!include MATERIAL/notifications.puml
!include FONTAWESOME/users.puml

LAYOUT_WITH_LEGEND()

Person(speaker, "Speaker", "Talk presenter") #green
Person(crew, "Crew", "Event Manager")  #red
Person(attendee, "Attendee", "Conference Attendee", $sprite="users") #brown
System_Boundary(container, "Conference Management System") {
    Container(webApplication, "Web application", "ReactJs/Angular", "Front end for all the users", $tags="webApp")
    Container(apiApplication, "API application", "Spring Boot", "API service to handle requests from web application", $tags="backendApp")
    ContainerDb(database, "Database", "No-Sql Database","Database to persist", $tags="db")
    Container(storage, "Cloud Storage", "S3","Storage for images/banner/ppt/archivals", $tags="files")
}

Container_Ext(socialNetwork, "Social Network", "Software System", "For branding via Facebook, Instagram, Twitter etc", $sprite="facebook")
Container_Ext(notification, "Notification System", "Software System", $sprite="notifications")
Container_Ext(payment, "Payment Gateway", "technology", "To Handle booking payments", $sprite="payment")

Rel(speaker, webApplication, "Uses", "Web Portal")
Rel(crew, webApplication, "Uses", "Web Portal")
Rel(attendee, webApplication, "Uses", "Web Portal")
Rel(apiApplication, socialNetwork, "Publish Upcoming conferences", "Uses API")
Rel(apiApplication, payment, "Uses", "API for transaction")
Rel(apiApplication, notification, "Sends notifications", "Notification Topic")
Rel(webApplication, apiApplication, "Make API calls", "HTTPS/JSON")
Rel(apiApplication, database, "Fetch data", "SQL")
Rel(apiApplication, storage, "Fetch files", "REST Call")
@enduml
