@startuml context
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons
!define DEVICONS2 https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons2
!define MATERIAL https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/material
!define FONTAWESOME https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome-5
!include DEVICONS/angular.puml
!include DEVICONS2/facebook.puml
!include MATERIAL/notifications.puml
!include FONTAWESOME/users.puml

LAYOUT_WITH_LEGEND()

System_Boundary(context, "Context") {
    Person(speaker, "Speaker", "Talk presenter") #green
    Person(crew, "Crew", "Event Manager")  #red
    Person(attendee, "Attendee", "Conference Attendee", $sprite="users") #brown
    Container(container, "Conference Management System", "Software System", "Manage conference details", $sprite="angular")
}

Container_Ext(crewExtContainer, "Social Network", "Software System", "For branding via Facebook, Instagram, Twitter etc", $sprite="facebook")
Container_Ext(notification, "Notification System", "Software System", $sprite="notifications")
Container_Ext(payment, "Payment Gateway", "technology", "To Handle booking payments", $sprite="payment")



Rel(speaker, container, "Uses", "Web Portal")
Rel(crew, container, "Uses", "Web Portal")
Rel(container, crewExtContainer, "Publish Upcoming conferences", "Uses API")
Rel(attendee, container, "Uses", "Web Portal")
Rel(container, payment, "Uses", "API for transaction")
Rel(container, notification, "Sends notifications", "Notification Topic")
@enduml
